### PR TITLE
Sundry minor refactoring for compliance with Ruby style guide

### PR DESCRIPTION
**Pull request by earthrid**
Incorporates reversions from previous pull request, as discussed.

### CODE REVIEW

**Comment by earthrid** [comment]
Resubmitting combined pull request. Thank you for your time and I hope this is now of use.

**Comment by kytrinyx** [comment]
Yepp, I'll pull this in. Thanks!

For future reference, you can use `git push --force` to update existing pull requests rather than creating a new one.

**Comment by kytrinyx** [comment]
Merged in 16b7dc11aa474c6cfddce9d8ab0fb819627aa7f1 -- I squashed the commits.

**Comment by earthrid** [comment]
> For future reference, you can use git push --force to update existing pull requests rather than creating a new one

Thanks, yes, I did try that approach but couldn’t quite get it to work. :)

**Comment by kytrinyx** [comment]
Hah. Yeah, git gets tricky! Cheers

**Pull request closed without merging**
